from praktikum.ingredient_types import INGREDIENT_TYPE_SAUCE, INGREDIENT_TYPE_FILLING

class BunTestData:

    BUN_CORRECT_NAME = 'saturn bun'
    BUN_CORRECT_PRICE = 5.43
    BUN_CORRECT_DATA = (BUN_CORRECT_NAME, BUN_CORRECT_PRICE) 

# class BurgerTestData:

class IngredientTestData:
    INGREDIENT_NAME_1 = 'milky way sauce'
    INGREDIENT_PRICE_1 = 17.75
    INGREDIENT_NAME_2 = 'mars volcano lava'
    INGREDIENT_PRICE_2 = 164.13
    INGREDIENT_CORRECT_DATA_1 = (INGREDIENT_TYPE_SAUCE, INGREDIENT_NAME_1, INGREDIENT_PRICE_1)
    INGREDIENT_CORRECT_DATA_2 = (INGREDIENT_TYPE_FILLING, INGREDIENT_NAME_2, INGREDIENT_PRICE_2)

# class DatabaseTestData: